package com.efun.po;
// Generated 2018-9-25 15:28:03 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TActivityRecruitmentInviteCode generated by hbm2java
 */
public class TActivityRecruitmentInviteCode implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private String inviteCode;
	private String inviter;
	private Short deleted;
	private Date createdTime;
	private Date modifiedTime;
	private Integer usageCount;

	public TActivityRecruitmentInviteCode() {
	}

	public TActivityRecruitmentInviteCode(String inviteCode, String inviter, Short deleted, Date createdTime,
			Date modifiedTime, Integer usageCount) {
		this.inviteCode = inviteCode;
		this.inviter = inviter;
		this.deleted = deleted;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.usageCount = usageCount;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getInviteCode() {
		return this.inviteCode;
	}

	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode;
	}

	public String getInviter() {
		return this.inviter;
	}

	public void setInviter(String inviter) {
		this.inviter = inviter;
	}

	public Short getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Short deleted) {
		this.deleted = deleted;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public Integer getUsageCount() {
		return this.usageCount;
	}

	public void setUsageCount(Integer usageCount) {
		this.usageCount = usageCount;
	}

}
