package com.efun.po;
// Generated 2017-10-11 16:59:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TActivityRewardReport generated by hbm2java
 */
public class TActivityRewardReport implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private String gameCode;
	private String activityCode;
	private String eventCode;
	private String eventName;
	private long loginId;
	private long uid;
	private String serverCode;
	private String serverName;
	private String roleId;
	private String roleName;
	private String userName;
	private String source;
	private String type;
	private String subType;
	private Date operatingTime;
	private String remark;
	private String statType;// 统计类型
	private long uniqueCounts;// 参与人数
	private long counts;// 参与人次
	private String startTime;
	private String endTime;
	private String checkboxType;
	private String checkboxSource;
	private String viewType;

	public TActivityRewardReport() {
	}

	public TActivityRewardReport(String gameCode, String activityCode, long loginId, long uid, String source,
			String type, String subType, Date operatingTime) {
		this.gameCode = gameCode;
		this.activityCode = activityCode;
		this.loginId = loginId;
		this.uid = uid;
		this.source = source;
		this.type = type;
		this.subType = subType;
		this.operatingTime = operatingTime;
	}

	public TActivityRewardReport(String gameCode, String activityCode, String eventCode, String eventName, long loginId,
			long uid, String serverCode, String serverName, String roleId, String roleName, String userName,
			String source, String type, String subType, Date operatingTime, String remark) {
		this.gameCode = gameCode;
		this.activityCode = activityCode;
		this.eventCode = eventCode;
		this.eventName = eventName;
		this.loginId = loginId;
		this.uid = uid;
		this.serverCode = serverCode;
		this.serverName = serverName;
		this.roleId = roleId;
		this.roleName = roleName;
		this.userName = userName;
		this.source = source;
		this.type = type;
		this.subType = subType;
		this.operatingTime = operatingTime;
		this.remark = remark;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGameCode() {
		return this.gameCode;
	}

	public void setGameCode(String gameCode) {
		this.gameCode = gameCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public String getEventCode() {
		return this.eventCode;
	}

	public void setEventCode(String eventCode) {
		this.eventCode = eventCode;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public long getLoginId() {
		return this.loginId;
	}

	public void setLoginId(long loginId) {
		this.loginId = loginId;
	}

	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public String getServerCode() {
		return this.serverCode;
	}

	public void setServerCode(String serverCode) {
		this.serverCode = serverCode;
	}

	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSubType() {
		return this.subType;
	}

	public void setSubType(String subType) {
		this.subType = subType;
	}

	public Date getOperatingTime() {
		return this.operatingTime;
	}

	public void setOperatingTime(Date operatingTime) {
		this.operatingTime = operatingTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getStatType() {
		return statType;
	}

	public void setStatType(String statType) {
		this.statType = statType;
	}

	public long getUniqueCounts() {
		return uniqueCounts;
	}

	public void setUniqueCounts(long uniqueCounts) {
		this.uniqueCounts = uniqueCounts;
	}

	public long getCounts() {
		return counts;
	}

	public void setCounts(long counts) {
		this.counts = counts;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getCheckboxType() {
		return checkboxType;
	}

	public void setCheckboxType(String checkboxType) {
		this.checkboxType = checkboxType;
	}

	public String getCheckboxSource() {
		return checkboxSource;
	}

	public void setCheckboxSource(String checkboxSource) {
		this.checkboxSource = checkboxSource;
	}

	public String getViewType() {
		return viewType;
	}

	public void setViewType(String viewType) {
		this.viewType = viewType;
	}

}
