package com.efun.po;
// Generated 2018-9-11 10:51:13 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TActivityRecruitment generated by hbm2java
 */
public class TActivityRecruitment implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private String name;
	private String phoneNumber;
	private String email;
	private String schoolName;
	private Short graduationYear;
	private String educationDegree;
	private String recruitType;
	private String postType;
	private String position;
	private String province;
	private String city;
	private String informationSource;
	private Date createdTime;
	private Date modifiedTime;
	private Short deleted;
	private String resumeFilePath;
	private String resumeFileName;
	private String inviteCode;
	private String status;
	private Date interviewTime;
	private Short isReply;

	public TActivityRecruitment() {
	}

	public TActivityRecruitment(String name, String phoneNumber, String email, String schoolName, Short graduationYear,
			String educationDegree, String recruitType, String postType, String position, String province, String city,
			String informationSource, Date createdTime, Date modifiedTime, Short deleted, String resumeFilePath,
			String resumeFileName, String inviteCode, String status, Date interviewTime, Short isReply) {
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.schoolName = schoolName;
		this.graduationYear = graduationYear;
		this.educationDegree = educationDegree;
		this.recruitType = recruitType;
		this.postType = postType;
		this.position = position;
		this.province = province;
		this.city = city;
		this.informationSource = informationSource;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.deleted = deleted;
		this.resumeFilePath = resumeFilePath;
		this.resumeFileName = resumeFileName;
		this.inviteCode = inviteCode;
		this.status = status;
		this.interviewTime = interviewTime;
		this.isReply = isReply;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	public Short getGraduationYear() {
		return this.graduationYear;
	}

	public void setGraduationYear(Short graduationYear) {
		this.graduationYear = graduationYear;
	}

	public String getEducationDegree() {
		return this.educationDegree;
	}

	public void setEducationDegree(String educationDegree) {
		this.educationDegree = educationDegree;
	}

	public String getRecruitType() {
		return this.recruitType;
	}

	public void setRecruitType(String recruitType) {
		this.recruitType = recruitType;
	}

	public String getPostType() {
		return this.postType;
	}

	public void setPostType(String postType) {
		this.postType = postType;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getInformationSource() {
		return this.informationSource;
	}

	public void setInformationSource(String informationSource) {
		this.informationSource = informationSource;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public Short getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Short deleted) {
		this.deleted = deleted;
	}

	public String getResumeFilePath() {
		return this.resumeFilePath;
	}

	public void setResumeFilePath(String resumeFilePath) {
		this.resumeFilePath = resumeFilePath;
	}

	public String getResumeFileName() {
		return this.resumeFileName;
	}

	public void setResumeFileName(String resumeFileName) {
		this.resumeFileName = resumeFileName;
	}

	public String getInviteCode() {
		return this.inviteCode;
	}

	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getInterviewTime() {
		return this.interviewTime;
	}

	public void setInterviewTime(Date interviewTime) {
		this.interviewTime = interviewTime;
	}

	public Short getIsReply() {
		return this.isReply;
	}

	public void setIsReply(Short isReply) {
		this.isReply = isReply;
	}

}
