package com.efun.po;

import java.math.BigDecimal;

/**
 * TCashflowProductPrice generated by hbm2java
 */
public class TCashflowProductPrice implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private BigDecimal price;
	private String cashflow;
	private String deleted;

	public TCashflowProductPrice() {
	}

	public TCashflowProductPrice(String title, BigDecimal price, String cashflow, String deleted) {
		this.title = title;
		this.price = price;
		this.cashflow = cashflow;
		this.deleted = deleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getCashflow() {
		return this.cashflow;
	}

	public void setCashflow(String cashflow) {
		this.cashflow = cashflow;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

}
