package com.efun.po;
// Generated 2017-11-7 17:15:00 by Hibernate Tools 5.2.3.Final

/**
 * TCashflowKrwGame generated by hbm2java
 */
public class TCashflowKrwGame implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String gameCode;
	private String cashflow;
	private String deleted;

	public TCashflowKrwGame() {
	}

	public TCashflowKrwGame(String gameCode, String cashflow, String deleted) {
		this.gameCode = gameCode;
		this.cashflow = cashflow;
		this.deleted = deleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGameCode() {
		return this.gameCode;
	}

	public void setGameCode(String gameCode) {
		this.gameCode = gameCode;
	}

	public String getCashflow() {
		return this.cashflow;
	}

	public void setCashflow(String cashflow) {
		this.cashflow = cashflow;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

}
