package com.efun.po;
// Generated 2018-10-17 10:38:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TRiskIforestWhitelist generated by hbm2java
 */
public class TRiskIforestWhitelist implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private String gameCode;
	private Long userId;
	private String ip;
	private String device;
	private Date createdTime;
	private Date modifiedTime;
	private String createdUser;
	private String modifiedUser;
	private boolean deleted;
	private String comment;

	public TRiskIforestWhitelist() {
	}

	public TRiskIforestWhitelist(String gameCode, Date createdTime, Date modifiedTime, String createdUser,
			String modifiedUser, boolean deleted) {
		this.gameCode = gameCode;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
	}

	public TRiskIforestWhitelist(String gameCode, Long userId, String ip, String device, Date createdTime,
			Date modifiedTime, String createdUser, String modifiedUser, boolean deleted, String comment) {
		this.gameCode = gameCode;
		this.userId = userId;
		this.ip = ip;
		this.device = device;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGameCode() {
		return this.gameCode;
	}

	public void setGameCode(String gameCode) {
		this.gameCode = gameCode;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public String getModifiedUser() {
		return this.modifiedUser;
	}

	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
