package com.efun.po;

// Generated 2018-7-10 11:35:24 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TRiskIforestConfig generated by hbm2java
 */
public class TRiskIforestConfig implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private double contamination;
	private Double loginLevel1;
	private Double loginLevel2;
	private Double registerLevel1;
	private Double registerLevel2;
	private Date createdTime;
	private Date modifiedTime;
	private String createdUser;
	private String modifiedUser;
	private String deleted;
	private String comment;

	public TRiskIforestConfig() {
	}

	public TRiskIforestConfig(double contamination, Date createdTime, Date modifiedTime, String createdUser,
			String modifiedUser, String deleted) {
		this.contamination = contamination;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
	}

	public TRiskIforestConfig(double contamination, Double loginLevel1, Double loginLevel2, Double registerLevel1,
			Double registerLevel2, Date createdTime, Date modifiedTime, String createdUser, String modifiedUser,
			String deleted, String comment) {
		this.contamination = contamination;
		this.loginLevel1 = loginLevel1;
		this.loginLevel2 = loginLevel2;
		this.registerLevel1 = registerLevel1;
		this.registerLevel2 = registerLevel2;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public double getContamination() {
		return this.contamination;
	}

	public void setContamination(double contamination) {
		this.contamination = contamination;
	}

	public Double getLoginLevel1() {
		return this.loginLevel1;
	}

	public void setLoginLevel1(Double loginLevel1) {
		this.loginLevel1 = loginLevel1;
	}

	public Double getLoginLevel2() {
		return this.loginLevel2;
	}

	public void setLoginLevel2(Double loginLevel2) {
		this.loginLevel2 = loginLevel2;
	}

	public Double getRegisterLevel1() {
		return this.registerLevel1;
	}

	public void setRegisterLevel1(Double registerLevel1) {
		this.registerLevel1 = registerLevel1;
	}

	public Double getRegisterLevel2() {
		return this.registerLevel2;
	}

	public void setRegisterLevel2(Double registerLevel2) {
		this.registerLevel2 = registerLevel2;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public String getModifiedUser() {
		return this.modifiedUser;
	}

	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
