package com.efun.po;
// Generated 2018-9-26 10:46:14 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TRiskIforestGameConfig generated by hbm2java
 */
public class TRiskIforestGameConfig implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private String gameCode;
	private String gameName;
	private String ipWhiteList;
	private String banIp;
	private String banDevice;
	private String banAccount;
	private Date createdTime;
	private Date modifiedTime;
	private String createdUser;
	private String modifiedUser;
	private boolean deleted;
	private String comment;

	public TRiskIforestGameConfig() {
	}

	public TRiskIforestGameConfig(String gameCode, Date createdTime, Date modifiedTime, String createdUser,
			String modifiedUser, boolean deleted) {
		this.gameCode = gameCode;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
	}

	public TRiskIforestGameConfig(String gameCode, String gameName, String ipWhiteList, String banIp,
			String banDevice, String banAccount, Date createdTime, Date modifiedTime, String createdUser,
			String modifiedUser, boolean deleted, String comment) {
		this.gameCode = gameCode;
		this.gameName = gameName;
		this.ipWhiteList = ipWhiteList;
		this.banIp = banIp;
		this.banDevice = banDevice;
		this.banAccount = banAccount;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGameCode() {
		return this.gameCode;
	}

	public void setGameCode(String gameCode) {
		this.gameCode = gameCode;
	}

	public String getGameName() {
		return this.gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	public String getIpWhiteList() {
		return this.ipWhiteList;
	}

	public void setIpWhiteList(String ipWhiteList) {
		this.ipWhiteList = ipWhiteList;
	}

	public String getBanIp() {
		return this.banIp;
	}

	public void setBanIp(String banIp) {
		this.banIp = banIp;
	}

	public String getBanDevice() {
		return this.banDevice;
	}

	public void setBanDevice(String banDevice) {
		this.banDevice = banDevice;
	}

	public String getBanAccount() {
		return this.banAccount;
	}

	public void setBanAccount(String banAccount) {
		this.banAccount = banAccount;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public String getModifiedUser() {
		return this.modifiedUser;
	}

	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
