package com.efun.po;

// Generated 2018-7-10 11:35:24 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TRiskIpRegisterConfig generated by hbm2java
 */
public class TRiskIpRegisterConfig implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Long id;
	private String gameCode;
	private String gameName;
	private String accountLimited;
	private String ipLimited;
	private String mailNotice;
	private String noticeUser;
	private String limitsRule;
	private String areaCode;
	private String ipWhiteList;
	private Date createdTime;
	private Date modifiedTime;
	private String createdUser;
	private String modifiedUser;
	private String deleted;
	private String comment;

	public TRiskIpRegisterConfig() {
	}

	public TRiskIpRegisterConfig(String gameCode, String accountLimited, String ipLimited, String mailNotice,
			String noticeUser, String limitsRule, String areaCode, Date createdTime, Date modifiedTime,
			String createdUser, String modifiedUser, String deleted) {
		this.gameCode = gameCode;
		this.accountLimited = accountLimited;
		this.ipLimited = ipLimited;
		this.mailNotice = mailNotice;
		this.noticeUser = noticeUser;
		this.limitsRule = limitsRule;
		this.areaCode = areaCode;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
	}

	public TRiskIpRegisterConfig(String gameCode, String gameName, String accountLimited, String ipLimited,
			String mailNotice, String noticeUser, String limitsRule, String areaCode, String ipWhiteList,
			Date createdTime, Date modifiedTime, String createdUser, String modifiedUser, String deleted,
			String comment) {
		this.gameCode = gameCode;
		this.gameName = gameName;
		this.accountLimited = accountLimited;
		this.ipLimited = ipLimited;
		this.mailNotice = mailNotice;
		this.noticeUser = noticeUser;
		this.limitsRule = limitsRule;
		this.areaCode = areaCode;
		this.ipWhiteList = ipWhiteList;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.createdUser = createdUser;
		this.modifiedUser = modifiedUser;
		this.deleted = deleted;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGameCode() {
		return this.gameCode;
	}

	public void setGameCode(String gameCode) {
		this.gameCode = gameCode;
	}

	public String getGameName() {
		return this.gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	public String getAccountLimited() {
		return accountLimited;
	}

	public void setAccountLimited(String accountLimited) {
		this.accountLimited = accountLimited;
	}

	public String getIpLimited() {
		return ipLimited;
	}

	public void setIpLimited(String ipLimited) {
		this.ipLimited = ipLimited;
	}

	public String getMailNotice() {
		return mailNotice;
	}

	public void setMailNotice(String mailNotice) {
		this.mailNotice = mailNotice;
	}
	
	public String getNoticeUser() {
		return this.noticeUser;
	}

	public void setNoticeUser(String noticeUser) {
		this.noticeUser = noticeUser;
	}

	public String getLimitsRule() {
		return this.limitsRule;
	}

	public void setLimitsRule(String limitsRule) {
		this.limitsRule = limitsRule;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getIpWhiteList() {
		return this.ipWhiteList;
	}

	public void setIpWhiteList(String ipWhiteList) {
		this.ipWhiteList = ipWhiteList;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public String getModifiedUser() {
		return this.modifiedUser;
	}

	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
